const Products = [
  {
    id: 1,
    type: 1,
    name: 'Bacha Inoxidable',
    brand: 'Ferrum',
    size: '42x10',
    description: 'Bacha doble con regilla',
    price: 12000,
    stock: 500,
    minStockQuantity: 5,
    discontinued: false,
    disabled: false,
  },
  {
    id: 2,
    type: 1,
    name: 'Bacha X675',
    brand: 'Roca',
    size: '75x18',
    description: 'Bacha simple con triturador y boquilla inoxidable',
    price: 35000,
    stock: 100,
    minStockQuantity: 2,
    discontinued: true,
    disabled: true,
  },
  {
    id: 3,
    type: 1,
    name: 'Zocalo',
    brand: '',
    size: '80x20',
    description: 'Negro Brazil',
    price: 2100,
    stock: 1000,
    minStockQuantity: 10,
    discontinued: true,
    disabled: false,
  },
  { id: 4, type: 2, name: 'Negro Brazil', discontinued: false },
  { id: 5, type: 2, name: 'Verde Jade', discontinued: true },
];

export default Products;
